AutostartDescription = "deej will launch at startup"
AutostartTitle = "Run at startup"
ComPortConnectedNotificationDescription = "Succesfully connected to deej."
ComPortConnectedNotificationTitle = "Connected to {{.ComPort}}."
ComPortDisconnectedNotificationDescription = "Trying to reconnect."
ComPortDisconnectedNotificationTitle = "Disconnected from {{.ComPort}} due to an error."
ConfigErrorDescription = "Please check deej's logs for more details."
ConfigErrorTitle = "Error loading configuration!"
ConfigInvalidDescription = "Please make sure {{.FilePath}} is in a valid YAML format."
ConfigInvalidTitle = "Invalid configuration!"
ConfigNotFoundDescription = "{{.FilePath}} must be in the same directory as deej. Please re-launch."
ConfigNotFoundTitle = "Can't find configuration!"
ConfigReloadDescription = "Your changes have been applied."
ConfigReloadTitle = "Configuration reloaded!"
EditConfigDescription = "Open config file with notepad"
EditConfigTitle = "Edit configuration"
QuitDescription = "Stop deej and quit"
QuitTitle = "Quit"
SettingsDescription = "Settings"
SettingsTitle = "Settings"
StatusFalseTitle = "Waiting for device..."
StatusTrueTitle = "Connected to {{.ComPort}}"

[AudioSessionsCount]
one = "{{.Count}} audio session"
other = "{{.Count}} audio sessions"
